In [57]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [58]:
df=pd.read_csv('news.csv', index_col=None)

In [59]:
df

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...,...
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL


In [60]:
dataset=df.drop("Unnamed: 0",axis=1)

In [61]:
dataset

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL


In [62]:
y=dataset["label"]

In [63]:
x=dataset["text"]

In [64]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=53)

In [65]:
from sklearn.feature_extraction.text import HashingVectorizer

# Create vectorizer
hash_vectorizer = HashingVectorizer(
    stop_words='english',
    n_features=5000,
    alternate_sign=False   # IMPORTANT for Naive Bayes
)

# Transform training data (NO fit_transform)
hash_train = hash_vectorizer.transform(X_train)

print(hash_train)   # Sparse matrix

# Transform test data
hash_test = hash_vectorizer.transform(X_test)


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1069421 stored elements and shape (4244, 5000)>
  Coords	Values
  (1, 48)	0.2672612419124244
  (1, 292)	0.1336306209562122
  (1, 335)	0.2672612419124244
  (1, 667)	0.1336306209562122
  (1, 1070)	0.1336306209562122
  (1, 1208)	0.1336306209562122
  (1, 1410)	0.1336306209562122
  (1, 1562)	0.1336306209562122
  (1, 1579)	0.2672612419124244
  (1, 1838)	0.1336306209562122
  (1, 1856)	0.1336306209562122
  (1, 1932)	0.2672612419124244
  (1, 2603)	0.1336306209562122
  (1, 2789)	0.1336306209562122
  (1, 2953)	0.1336306209562122
  (1, 2976)	0.2672612419124244
  (1, 3002)	0.2672612419124244
  (1, 3488)	0.1336306209562122
  (1, 3857)	0.1336306209562122
  (1, 4045)	0.1336306209562122
  (1, 4197)	0.5345224838248488
  (1, 4340)	0.1336306209562122
  (1, 4559)	0.1336306209562122
  (2, 197)	0.3333333333333333
  (2, 1353)	0.3333333333333333
  :	:
  (4243, 4261)	0.028149476494978783
  (4243, 4262)	0.1688968589698727
  (4243, 4283)	0.028149476494

In [66]:
print(hash_train .toarray())

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.04428074 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [67]:
# Import Libraries

import pandas as pd
from sklearn import metrics

# Machine Learning Models
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression, PassiveAggressiveClassifier
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score



In [68]:
models = {
    "Naive Bayes": MultinomialNB(),
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "SVM": SVC(kernel='linear'),
    "Random Forest": RandomForestClassifier()
}

results = {}

for name, model in models.items():
    model.fit(hash_train, y_train)
    pred = model.predict(hash_test)
    acc = accuracy_score(y_test, pred)
    results[name] = acc
    print(f"{name} Accuracy: {acc:.4f}")

Naive Bayes Accuracy: 0.8694
Logistic Regression Accuracy: 0.8934
SVM Accuracy: 0.9106
Random Forest Accuracy: 0.9005


In [69]:
# Store results
results = []

# Train and evaluate each model
for name, clf in models.items():

    print("\n==============================")
    print("Model:", name)

    # Train model
    clf.fit(hash_train , y_train)

    # Predict
    pred = clf.predict(hash_test)

    # Accuracy
    score = metrics.accuracy_score(y_test , pred)
    print("Accuracy: %0.3f" % score)

    # Confusion Matrix
    cm = metrics.confusion_matrix(y_test , pred, labels=['FAKE','REAL'])
    print("Confusion Matrix:")
    print(cm)

    # Save result
    results.append([name, score])


Model: Naive Bayes
Accuracy: 0.869
Confusion Matrix:
[[866 142]
 [131 952]]

Model: Logistic Regression
Accuracy: 0.893
Confusion Matrix:
[[934  74]
 [149 934]]

Model: SVM
Accuracy: 0.911
Confusion Matrix:
[[943  65]
 [122 961]]

Model: Random Forest
Accuracy: 0.906
Confusion Matrix:
[[934  74]
 [122 961]]


In [70]:
results_df = pd.DataFrame(results, columns=["Model","Accuracy"])

results_df = results_df.sort_values(by="Accuracy", ascending=False)

print("\nModel Comparison Table")
print(results_df)


Model Comparison Table
                 Model  Accuracy
2                  SVM  0.910569
3        Random Forest  0.906265
1  Logistic Regression  0.893352
0          Naive Bayes  0.869440


In [71]:
# Get best model name
best_model_name = results_df.iloc[0]["Model"]

print("Best Model:", best_model_name)

# Get the best model object
best_model = models[best_model_name]

Best Model: SVM


In [72]:
best_model.fit(hash_train, y_train)

,C,1.0
,kernel,'linear'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,False
,tol,0.001
,cache_size,200
,class_weight,None
,verbose,False


In [49]:
best_pred = best_model.predict(hash_test )

accuracy = metrics.accuracy_score(y_test, best_pred)

print("Best Model Accuracy:", accuracy)

Best Model Accuracy: 0.9344811095169775


In [33]:
cm = metrics.confusion_matrix(y_test, best_pred, labels=['FAKE','REAL'])

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[965  43]
 [ 94 989]]


In [34]:
dataset["text"][0]

'Daniel Greenfield, a Shillman Journalism Fellow at the Freedom Center, is a New York writer focusing on radical Islam. \nIn the final stretch of the election, Hillary Rodham Clinton has gone to war with the FBI. \nThe word “unprecedented” has been thrown around so often this election that it ought to be retired. But it’s still unprecedented for the nominee of a major political party to go war with the FBI. \nBut that’s exactly what Hillary and her people have done. Coma patients just waking up now and watching an hour of CNN from their hospital beds would assume that FBI Director James Comey is Hillary’s opponent in this election. \nThe FBI is under attack by everyone from Obama to CNN. Hillary’s people have circulated a letter attacking Comey. There are currently more media hit pieces lambasting him than targeting Trump. It wouldn’t be too surprising if the Clintons or their allies were to start running attack ads against the FBI. \nThe FBI’s leadership is being warned that the entir

In [50]:
hash_train [[0]]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 0 stored elements and shape (1, 5000)>

In [51]:
from sklearn.feature_extraction.text import HashingVectorizer

# Create vectorizer
hash_vectorizer = HashingVectorizer(
    stop_words='english',
    n_features=5000,
    alternate_sign=False   # IMPORTANT for Naive Bayes
)

# Transform training data (NO fit_transform)
hash_train = hash_vectorizer.transform(X_train)

print(hash_train)   # Sparse matrix

# Transform test data
hash_test = hash_vectorizer.transform(X_test)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1069421 stored elements and shape (4244, 5000)>
  Coords	Values
  (1, 48)	0.2672612419124244
  (1, 292)	0.1336306209562122
  (1, 335)	0.2672612419124244
  (1, 667)	0.1336306209562122
  (1, 1070)	0.1336306209562122
  (1, 1208)	0.1336306209562122
  (1, 1410)	0.1336306209562122
  (1, 1562)	0.1336306209562122
  (1, 1579)	0.2672612419124244
  (1, 1838)	0.1336306209562122
  (1, 1856)	0.1336306209562122
  (1, 1932)	0.2672612419124244
  (1, 2603)	0.1336306209562122
  (1, 2789)	0.1336306209562122
  (1, 2953)	0.1336306209562122
  (1, 2976)	0.2672612419124244
  (1, 3002)	0.2672612419124244
  (1, 3488)	0.1336306209562122
  (1, 3857)	0.1336306209562122
  (1, 4045)	0.1336306209562122
  (1, 4197)	0.5345224838248488
  (1, 4340)	0.1336306209562122
  (1, 4559)	0.1336306209562122
  (2, 197)	0.3333333333333333
  (2, 1353)	0.3333333333333333
  :	:
  (4243, 4261)	0.028149476494978783
  (4243, 4262)	0.1688968589698727
  (4243, 4283)	0.028149476494

In [52]:
hash_train[[0]]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 0 stored elements and shape (1, 5000)>

In [73]:
X_train[[0]]

0    Daniel Greenfield, a Shillman Journalism Fello...
Name: text, dtype: object

In [74]:
clf.predict(hash_train[[0]])

array(['FAKE'], dtype=object)

In [75]:
clf.predict(hash_train[[30]])

array(['REAL'], dtype=object)